// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MockEUR$Type } from "./MockEUR";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockEUR"]: MockEUR$Type;
    ["contracts/MockEUR.sol:MockEUR"]: MockEUR$Type;
  }

  interface ContractTypesMap {
    ["MockEUR"]: GetContractReturnType<MockEUR$Type["abi"]>;
    ["contracts/MockEUR.sol:MockEUR"]: GetContractReturnType<MockEUR$Type["abi"]>;
  }
}
