// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC20$Type } from "./IERC20";
import { LoanlyMarketplace$Type } from "./LoanlyMarketplace";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC20"]: IERC20$Type;
    ["LoanlyMarketplace"]: LoanlyMarketplace$Type;
    ["contracts/LoanlyMarketplace.sol:IERC20"]: IERC20$Type;
    ["contracts/LoanlyMarketplace.sol:LoanlyMarketplace"]: LoanlyMarketplace$Type;
  }

  interface ContractTypesMap {
    ["IERC20"]: GetContractReturnType<IERC20$Type["abi"]>;
    ["LoanlyMarketplace"]: GetContractReturnType<LoanlyMarketplace$Type["abi"]>;
    ["contracts/LoanlyMarketplace.sol:IERC20"]: GetContractReturnType<IERC20$Type["abi"]>;
    ["contracts/LoanlyMarketplace.sol:LoanlyMarketplace"]: GetContractReturnType<LoanlyMarketplace$Type["abi"]>;
  }
}
